/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomId = IDL.Text;
export const LanguageCode = IDL.Text;
export const Time = IDL.Int;
export const SpeakerLabel = IDL.Text;
export const BridgeMessage = IDL.Record({
  'languageCode' : LanguageCode,
  'timestamp' : Time,
  'speaker' : SpeakerLabel,
  'payload' : IDL.Text,
});
export const SignalJson = IDL.Text;
export const SignalMessage = IDL.Record({
  'timestamp' : Time,
  'signal' : SignalJson,
});

export const idlService = IDL.Service({
  'checkRoomExists' : IDL.Func([RoomId], [IDL.Bool], ['query']),
  'ensureRoom' : IDL.Func([RoomId], [IDL.Bool], []),
  'fetchMessagesSinceForRoomId' : IDL.Func(
      [RoomId, IDL.Nat],
      [IDL.Vec(BridgeMessage)],
      ['query'],
    ),
  'fetchSignals' : IDL.Func(
      [RoomId, IDL.Nat],
      [IDL.Vec(SignalMessage)],
      ['query'],
    ),
  'sendToRoom' : IDL.Func(
      [
        RoomId,
        IDL.Record({
          'languageCode' : LanguageCode,
          'speaker' : SpeakerLabel,
          'payload' : IDL.Text,
        }),
      ],
      [IDL.Bool],
      [],
    ),
  'storeSignal' : IDL.Func([RoomId, SignalJson], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomId = IDL.Text;
  const LanguageCode = IDL.Text;
  const Time = IDL.Int;
  const SpeakerLabel = IDL.Text;
  const BridgeMessage = IDL.Record({
    'languageCode' : LanguageCode,
    'timestamp' : Time,
    'speaker' : SpeakerLabel,
    'payload' : IDL.Text,
  });
  const SignalJson = IDL.Text;
  const SignalMessage = IDL.Record({
    'timestamp' : Time,
    'signal' : SignalJson,
  });
  
  return IDL.Service({
    'checkRoomExists' : IDL.Func([RoomId], [IDL.Bool], ['query']),
    'ensureRoom' : IDL.Func([RoomId], [IDL.Bool], []),
    'fetchMessagesSinceForRoomId' : IDL.Func(
        [RoomId, IDL.Nat],
        [IDL.Vec(BridgeMessage)],
        ['query'],
      ),
    'fetchSignals' : IDL.Func(
        [RoomId, IDL.Nat],
        [IDL.Vec(SignalMessage)],
        ['query'],
      ),
    'sendToRoom' : IDL.Func(
        [
          RoomId,
          IDL.Record({
            'languageCode' : LanguageCode,
            'speaker' : SpeakerLabel,
            'payload' : IDL.Text,
          }),
        ],
        [IDL.Bool],
        [],
      ),
    'storeSignal' : IDL.Func([RoomId, SignalJson], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };