/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BridgeMessage {
  'languageCode' : LanguageCode,
  'timestamp' : Time,
  'speaker' : SpeakerLabel,
  'payload' : string,
}
export type LanguageCode = string;
export type RoomId = string;
export type SignalJson = string;
export interface SignalMessage { 'timestamp' : Time, 'signal' : SignalJson }
export type SpeakerLabel = string;
export type Time = bigint;
export interface _SERVICE {
  'checkRoomExists' : ActorMethod<[RoomId], boolean>,
  'ensureRoom' : ActorMethod<[RoomId], boolean>,
  'fetchMessagesSinceForRoomId' : ActorMethod<
    [RoomId, bigint],
    Array<BridgeMessage>
  >,
  'fetchSignals' : ActorMethod<[RoomId, bigint], Array<SignalMessage>>,
  'sendToRoom' : ActorMethod<
    [
      RoomId,
      {
        'languageCode' : LanguageCode,
        'speaker' : SpeakerLabel,
        'payload' : string,
      },
    ],
    boolean
  >,
  'storeSignal' : ActorMethod<[RoomId, SignalJson], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];